// Auto-generated

const defaultProducts = [
  // ===== SAUDI THOBES =====
  { id:1, cat:"thobe", img:"images/product_saudi_thobe.png",
    name_en:"Classic Saudi Thobe", name_ar:"ثوب سعودي كلاسيكي",
    desc_en:"Premium white Saudi thobe with mandarin collar, crafted from finest Japanese fabric. Custom-tailored to your exact measurements.",
    desc_ar:"ثوب سعودي أبيض فاخر بياقة ماندارين، مصنوع من أجود الأقمشة اليابانية. مفصّل حسب مقاساتك بالضبط.",
    price:350, old_price:450, badge:"Featured", sizes:["S","M","L","XL","XXL"] },
  { id:8, cat:"thobe", img:"images/product_saudi_thobe.png",
    name_en:"Royal Saudi Thobe", name_ar:"ثوب سعودي ملكي",
    desc_en:"Ultra-premium Saudi thobe with hand-stitched collar, French seams throughout. Bespoke tailoring included.",
    desc_ar:"ثوب سعودي فاخر جداً بياقة مخيطة يدوياً وخياطات فرنسية. خياطة مفصلة مشمولة.",
    price:550, old_price:700, badge:"Exclusive", sizes:["S","M","L","XL","XXL"] },
  { id:12, cat:"thobe", img:"images/product_saudi_thobe.png",
    name_en:"Summer Saudi Thobe", name_ar:"ثوب سعودي صيفي",
    desc_en:"Lightweight summer Saudi thobe with breathable fabric. Custom-tailored for hot weather comfort.",
    desc_ar:"ثوب سعودي صيفي خفيف بقماش يسمح بمرور الهواء. مفصّل للراحة في الأجواء الحارة.",
    price:290, old_price:0, badge:"New", sizes:["S","M","L","XL","XXL"] },

  // ===== EMIRATI THOBES (Kandura) =====
  { id:2, cat:"emirati", img:"images/product_emirati_thobe.png",
    name_en:"Classic Emirati Kandura", name_ar:"كندورة إماراتية كلاسيكية",
    desc_en:"Elegant Emirati style kandura with tassel (tarboosh) collar detail. Custom-tailored with premium Chinese fabric.",
    desc_ar:"كندورة إماراتية أنيقة بتفاصيل شراشيب (طربوش) الياقة. مفصّلة بأقمشة صينية فاخرة.",
    price:380, old_price:0, badge:"New", sizes:["S","M","L","XL","XXL"] },
  { id:13, cat:"emirati", img:"images/product_emirati_thobe.png",
    name_en:"Premium Emirati Kandura", name_ar:"كندورة إماراتية فاخرة",
    desc_en:"Premium Emirati kandura with gold-tipped tarboosh and cufflinks detail. Tailored to perfection with Japanese fabric.",
    desc_ar:"كندورة إماراتية فاخرة بطربوش مذهب وتفاصيل أزرار أكمام. مفصّلة بإتقان بقماش ياباني.",
    price:480, old_price:580, badge:"Premium", sizes:["S","M","L","XL","XXL"] },
  { id:14, cat:"emirati", img:"images/product_emirati_thobe.png",
    name_en:"Emirati Wedding Kandura", name_ar:"كندورة إماراتية للأعراس",
    desc_en:"Luxurious Emirati kandura for weddings and special occasions. Hand-embroidered collar with gold thread. Custom-made.",
    desc_ar:"كندورة إماراتية فاخرة للأعراس والمناسبات الخاصة. ياقة مطرزة يدوياً بخيط ذهبي. مصنوعة حسب الطلب.",
    price:650, old_price:0, badge:"Exclusive", sizes:["S","M","L","XL","XXL"] },
  { id:15, cat:"emirati", img:"images/product_emirati_thobe.png",
    name_en:"Everyday Emirati Kandura", name_ar:"كندورة إماراتية يومية",
    desc_en:"Comfortable everyday Emirati kandura with wrinkle-resistant fabric. Custom-tailored for daily wear.",
    desc_ar:"كندورة إماراتية مريحة للاستخدام اليومي بقماش مقاوم للتجعد. مفصّلة للارتداء اليومي.",
    price:320, old_price:0, badge:"", sizes:["S","M","L","XL","XXL"] },

  // ===== QATARI THOBES =====
  { id:3, cat:"qatari", img:"images/product_qatari_thobe.png",
    name_en:"Classic Qatari Thobe", name_ar:"ثوب قطري كلاسيكي",
    desc_en:"Distinguished Qatari style thobe with side pockets and unique collar design. Custom-tailored to your measurements.",
    desc_ar:"ثوب قطري مميز بجيوب جانبية وتصميم ياقة فريد. مفصّل حسب مقاساتك.",
    price:360, old_price:420, badge:"", sizes:["S","M","L","XL","XXL"] },
  { id:16, cat:"qatari", img:"images/product_qatari_thobe.png",
    name_en:"Premium Qatari Thobe", name_ar:"ثوب قطري فاخر",
    desc_en:"Premium Qatari thobe with distinctive collar and cuff design. Hand-stitched with finest Japanese fabric.",
    desc_ar:"ثوب قطري فاخر بتصميم ياقة وأكمام مميز. مخيط يدوياً بأجود الأقمشة اليابانية.",
    price:450, old_price:550, badge:"Premium", sizes:["S","M","L","XL","XXL"] },
  { id:17, cat:"qatari", img:"images/product_qatari_thobe.png",
    name_en:"Qatari Formal Thobe", name_ar:"ثوب قطري رسمي",
    desc_en:"Formal Qatari thobe for official occasions. Crisp finish with structured collar. Bespoke tailoring included.",
    desc_ar:"ثوب قطري رسمي للمناسبات الرسمية. لمسة أنيقة بياقة مهيكلة. خياطة مفصلة مشمولة.",
    price:520, old_price:0, badge:"New", sizes:["S","M","L","XL","XXL"] },
  { id:18, cat:"qatari", img:"images/product_qatari_thobe.png",
    name_en:"Qatari Summer Thobe", name_ar:"ثوب قطري صيفي",
    desc_en:"Lightweight Qatari summer thobe with breathable cotton blend. Perfect for Gulf summer. Custom-tailored.",
    desc_ar:"ثوب قطري صيفي خفيف بمزيج قطني يسمح بمرور الهواء. مثالي لصيف الخليج. مفصّل حسب الطلب.",
    price:340, old_price:0, badge:"", sizes:["S","M","L","XL","XXL"] },

  // ===== KUWAITI THOBES (Dishdasha) =====
  { id:4, cat:"kuwaiti", img:"images/product_kuwaiti_thobe.png",
    name_en:"Classic Kuwaiti Dishdasha", name_ar:"دشداشة كويتية كلاسيكية",
    desc_en:"Classic Kuwaiti dishdasha with two-button collar and chest pocket. Custom-tailored with premium fabric.",
    desc_ar:"دشداشة كويتية كلاسيكية بياقة بزرين وجيب صدري. مفصّلة بأقمشة فاخرة.",
    price:340, old_price:0, badge:"", sizes:["S","M","L","XL","XXL"] },
  { id:19, cat:"kuwaiti", img:"images/product_kuwaiti_thobe.png",
    name_en:"Premium Kuwaiti Dishdasha", name_ar:"دشداشة كويتية فاخرة",
    desc_en:"Premium Kuwaiti dishdasha with pearl buttons and French-stitched seams. Custom-made with Japanese fabric.",
    desc_ar:"دشداشة كويتية فاخرة بأزرار لؤلؤية وخياطات فرنسية. مصنوعة حسب الطلب بقماش ياباني.",
    price:460, old_price:550, badge:"Premium", sizes:["S","M","L","XL","XXL"] },
  { id:20, cat:"kuwaiti", img:"images/product_kuwaiti_thobe.png",
    name_en:"Kuwaiti Royal Dishdasha", name_ar:"دشداشة كويتية ملكية",
    desc_en:"Royal Kuwaiti dishdasha for formal events. Silk-blend fabric with hand-finished details. Bespoke tailoring.",
    desc_ar:"دشداشة كويتية ملكية للمناسبات الرسمية. قماش مخلوط بالحرير بتفاصيل يدوية. خياطة مفصلة.",
    price:600, old_price:0, badge:"Exclusive", sizes:["S","M","L","XL","XXL"] },
  { id:21, cat:"kuwaiti", img:"images/product_kuwaiti_thobe.png",
    name_en:"Kuwaiti Casual Dishdasha", name_ar:"دشداشة كويتية كاجوال",
    desc_en:"Comfortable casual Kuwaiti dishdasha for everyday wear. Soft cotton fabric, custom-tailored.",
    desc_ar:"دشداشة كويتية مريحة للاستخدام اليومي. قماش قطني ناعم، مفصّلة حسب الطلب.",
    price:280, old_price:0, badge:"New", sizes:["S","M","L","XL","XXL"] },

  // ===== JUBBAS =====
  { id:5, cat:"jubba", img:"images/product_jubba.png",
    name_en:"Premium Jubba", name_ar:"جُبة فاخرة",
    desc_en:"Cream jubba with elegant chest embroidery, perfect for special occasions.",
    desc_ar:"جُبة كريمية بتطريز صدري أنيق، مثالية للمناسبات الخاصة.",
    price:280, old_price:350, badge:"Sale", sizes:["S","M","L","XL","XXL"] },
  { id:9, cat:"jubba", img:"images/product_jubba.png",
    name_en:"Moroccan Jubba", name_ar:"جُبة مغربية",
    desc_en:"Elegant Moroccan-style jubba with intricate geometric embroidery.",
    desc_ar:"جُبة بأسلوب مغربي أنيق بتطريز هندسي معقد.",
    price:320, old_price:0, badge:"New", sizes:["S","M","L","XL","XXL"] },

  // ===== SAIDERIAS =====
  { id:6, cat:"saideria", img:"images/product_saideria.png",
    name_en:"Classic Saideria", name_ar:"صدرية كلاسيكية",
    desc_en:"Premium cotton saideria, the essential undergarment for your thobe.",
    desc_ar:"صدرية قطنية فاخرة، القطعة الأساسية تحت الثوب.",
    price:85, old_price:0, badge:"", sizes:["S","M","L","XL","XXL"] },
  { id:11, cat:"saideria", img:"images/product_saideria.png",
    name_en:"Premium Saideria Set (3 Pack)", name_ar:"طقم صداري فاخر (٣ قطع)",
    desc_en:"Set of 3 premium cotton saiderias in white. Essential undergarments.",
    desc_ar:"طقم ٣ صداري قطنية فاخرة باللون الأبيض. قطع أساسية.",
    price:200, old_price:250, badge:"Pack", sizes:["S","M","L","XL","XXL"] },

  // ===== FABRICS (20+ items) =====
  { id:7, cat:"fabric", img:"images/product_white_fabric.png",
    name_en:"Japanese Toyobo Premium White", name_ar:"قماش تويوبو ياباني أبيض فاخر",
    desc_en:"Premium Japanese Toyobo white fabric, 3.5m. Luxurious feel with subtle sheen. The gold standard of thobe fabrics.",
    desc_ar:"قماش تويوبو ياباني أبيض فاخر، ٣.٥ متر. ملمس فاخر مع لمعة خفيفة. المعيار الذهبي لأقمشة الثياب.",
    price:220, old_price:280, badge:"Premium", sizes:["3m","3.5m","4m","4.5m"] },
  { id:10, cat:"fabric", img:"images/product_white_fabric.png",
    name_en:"Chinese Premium Cotton", name_ar:"قطن صيني فاخر",
    desc_en:"High-quality Chinese cotton fabric, 3.5m. Breathable and comfortable for everyday thobes.",
    desc_ar:"قماش قطني صيني عالي الجودة، ٣.٥ متر. قابل للتنفس ومريح للثياب اليومية.",
    price:150, old_price:0, badge:"", sizes:["3m","3.5m","4m","4.5m"] },
  { id:22, cat:"fabric", img:"images/product_white_fabric.png",
    name_en:"Japanese Toyobo Royal", name_ar:"قماش تويوبو ياباني ملكي",
    desc_en:"Top-tier Japanese Toyobo Royal edition, 3.5m. Ultra-smooth with elegant drape. For premium custom thobes.",
    desc_ar:"قماش تويوبو ياباني إصدار ملكي فائق الجودة، ٣.٥ متر. ناعم جداً بانسدال أنيق. للثياب المفصّلة الفاخرة.",
    price:320, old_price:400, badge:"Best Seller", sizes:["3m","3.5m","4m","4.5m"] },
  { id:23, cat:"fabric", img:"images/product_white_fabric.png",
    name_en:"Japanese Toyobo Diamond", name_ar:"قماش تويوبو ياباني دايموند",
    desc_en:"Japanese Toyobo Diamond grade fabric, 3.5m. Crystal-like sheen with wrinkle resistance. Premium choice.",
    desc_ar:"قماش تويوبو ياباني درجة دايموند، ٣.٥ متر. لمعة كالكريستال مع مقاومة التجعد. الخيار الفاخر.",
    price:350, old_price:0, badge:"New", sizes:["3m","3.5m","4m","4.5m"] },
  { id:24, cat:"fabric", img:"images/product_white_fabric.png",
    name_en:"Japanese Getzner White", name_ar:"قماش جيتسنر ياباني أبيض",
    desc_en:"Japanese Getzner premium white fabric, 3.5m. Renowned for durability and color retention.",
    desc_ar:"قماش جيتسنر ياباني أبيض فاخر، ٣.٥ متر. مشهور بالمتانة وثبات اللون.",
    price:280, old_price:340, badge:"", sizes:["3m","3.5m","4m","4.5m"] },
  { id:25, cat:"fabric", img:"images/product_white_fabric.png",
    name_en:"Chinese Silky Cotton Blend", name_ar:"قماش صيني مزيج قطن حريري",
    desc_en:"Chinese silky cotton blend fabric, 3.5m. Soft touch with natural breathability. Great value for quality.",
    desc_ar:"قماش صيني مزيج قطن حريري، ٣.٥ متر. ملمس ناعم مع تهوية طبيعية. قيمة ممتازة للجودة.",
    price:130, old_price:0, badge:"", sizes:["3m","3.5m","4m","4.5m"] },
  { id:26, cat:"fabric", img:"images/product_white_fabric.png",
    name_en:"Chinese Royal Poplin", name_ar:"قماش بوبلين صيني ملكي",
    desc_en:"Chinese Royal Poplin fabric, 3.5m. Crisp finish with excellent structure. Ideal for formal thobes.",
    desc_ar:"قماش بوبلين صيني ملكي، ٣.٥ متر. لمسة نظيفة مع هيكل ممتاز. مثالي للثياب الرسمية.",
    price:160, old_price:200, badge:"Sale", sizes:["3m","3.5m","4m","4.5m"] },
  { id:27, cat:"fabric", img:"images/product_white_fabric.png",
    name_en:"Chinese Premium Twill", name_ar:"قماش تويل صيني فاخر",
    desc_en:"Premium Chinese twill weave fabric, 3.5m. Diagonal texture adds elegance. Suitable for all thobe styles.",
    desc_ar:"قماش تويل صيني فاخر منسوج، ٣.٥ متر. نسيج مائل يضيف أناقة. مناسب لجميع أنماط الثياب.",
    price:140, old_price:0, badge:"", sizes:["3m","3.5m","4m","4.5m"] },
  { id:28, cat:"fabric", img:"images/product_white_fabric.png",
    name_en:"Korean Premium White", name_ar:"قماش كوري أبيض فاخر",
    desc_en:"Korean premium white fabric, 3.5m. Excellent wrinkle resistance with modern finish. Popular choice.",
    desc_ar:"قماش كوري أبيض فاخر، ٣.٥ متر. مقاومة ممتازة للتجعد بلمسة عصرية. خيار شائع.",
    price:190, old_price:240, badge:"Popular", sizes:["3m","3.5m","4m","4.5m"] },
  { id:29, cat:"fabric", img:"images/product_white_fabric.png",
    name_en:"Korean Silk Touch", name_ar:"قماش كوري لمسة حرير",
    desc_en:"Korean Silk Touch fabric, 3.5m. Silky smooth finish with excellent drape. For elegant custom thobes.",
    desc_ar:"قماش كوري لمسة حرير، ٣.٥ متر. لمسة حريرية ناعمة مع انسدال ممتاز. للثياب المفصّلة الأنيقة.",
    price:210, old_price:0, badge:"", sizes:["3m","3.5m","4m","4.5m"] },
  { id:30, cat:"fabric", img:"images/product_white_fabric.png",
    name_en:"Turkish Cotton Satin", name_ar:"قماش قطن ساتان تركي",
    desc_en:"Turkish cotton satin fabric, 3.5m. Lustrous finish with exceptional softness. Imported from Istanbul.",
    desc_ar:"قماش قطن ساتان تركي، ٣.٥ متر. لمعة أنيقة مع نعومة استثنائية. مستورد من إسطنبول.",
    price:200, old_price:260, badge:"", sizes:["3m","3.5m","4m","4.5m"] },
  { id:31, cat:"fabric", img:"images/product_white_fabric.png",
    name_en:"Turkish Premium Linen Blend", name_ar:"قماش كتان تركي فاخر",
    desc_en:"Turkish linen-cotton blend fabric, 3.5m. Natural texture with superior breathability. Perfect for summer.",
    desc_ar:"قماش مزيج كتان وقطن تركي، ٣.٥ متر. ملمس طبيعي مع تهوية فائقة. مثالي للصيف.",
    price:180, old_price:0, badge:"New", sizes:["3m","3.5m","4m","4.5m"] },
  { id:32, cat:"fabric", img:"images/product_white_fabric.png",
    name_en:"Egyptian Cotton Supreme", name_ar:"قماش قطن مصري سوبريم",
    desc_en:"Egyptian long-staple cotton fabric, 3.5m. World-renowned quality with ultra-soft hand feel. Luxury tier.",
    desc_ar:"قماش قطن مصري طويل التيلة، ٣.٥ متر. جودة عالمية مع ملمس فائق النعومة. المستوى الفاخر.",
    price:260, old_price:320, badge:"Premium", sizes:["3m","3.5m","4m","4.5m"] },
  { id:33, cat:"fabric", img:"images/product_white_fabric.png",
    name_en:"Egyptian Cotton Classic", name_ar:"قماش قطن مصري كلاسيكي",
    desc_en:"Classic Egyptian cotton fabric, 3.5m. Reliable quality with smooth finish. Excellent for everyday thobes.",
    desc_ar:"قماش قطن مصري كلاسيكي، ٣.٥ متر. جودة موثوقة بلمسة ناعمة. ممتاز للثياب اليومية.",
    price:175, old_price:0, badge:"", sizes:["3m","3.5m","4m","4.5m"] },
  { id:34, cat:"fabric", img:"images/product_white_fabric.png",
    name_en:"Italian Wool Blend", name_ar:"قماش صوف إيطالي",
    desc_en:"Italian wool-blend fabric, 3.5m. Perfect for winter thobes. Warm yet lightweight with premium drape.",
    desc_ar:"قماش مزيج صوف إيطالي، ٣.٥ متر. مثالي لثياب الشتاء. دافئ وخفيف مع انسدال فاخر.",
    price:300, old_price:380, badge:"", sizes:["3m","3.5m","4m","4.5m"] },
  { id:35, cat:"fabric", img:"images/product_white_fabric.png",
    name_en:"European Swiss Voile", name_ar:"قماش فوال سويسري أوروبي",
    desc_en:"European Swiss Voile fabric, 3.5m. Extremely lightweight and sheer. Perfect for hot summer thobes.",
    desc_ar:"قماش فوال سويسري أوروبي، ٣.٥ متر. خفيف للغاية وشفاف. مثالي لثياب الصيف الحار.",
    price:240, old_price:0, badge:"", sizes:["3m","3.5m","4m","4.5m"] },
  { id:36, cat:"fabric", img:"images/product_white_fabric.png",
    name_en:"Indian Cotton Premium", name_ar:"قماش قطن هندي فاخر",
    desc_en:"Indian premium cotton fabric, 3.5m. Traditional quality with modern finish. Budget-friendly premium choice.",
    desc_ar:"قماش قطن هندي فاخر، ٣.٥ متر. جودة تقليدية بلمسة عصرية. خيار فاخر بسعر معقول.",
    price:110, old_price:140, badge:"Value", sizes:["3m","3.5m","4m","4.5m"] },
  { id:37, cat:"fabric", img:"images/product_white_fabric.png",
    name_en:"Indian Muslin Super Fine", name_ar:"قماش موسلين هندي ناعم جداً",
    desc_en:"Indian super fine muslin fabric, 3.5m. Ultra-light and breathable. Heritage weaving technique.",
    desc_ar:"قماش موسلين هندي ناعم جداً، ٣.٥ متر. خفيف جداً وقابل للتنفس. تقنية نسج تراثية.",
    price:120, old_price:0, badge:"", sizes:["3m","3.5m","4m","4.5m"] },
  { id:38, cat:"fabric", img:"images/product_white_fabric.png",
    name_en:"Japanese Toyobo Ivory", name_ar:"قماش تويوبو ياباني عاجي",
    desc_en:"Japanese Toyobo in elegant ivory shade, 3.5m. Subtle warm tone with same premium Toyobo quality.",
    desc_ar:"قماش تويوبو ياباني بلون عاجي أنيق، ٣.٥ متر. لون دافئ خفيف بنفس جودة تويوبو الفاخرة.",
    price:230, old_price:0, badge:"", sizes:["3m","3.5m","4m","4.5m"] },
  { id:39, cat:"fabric", img:"images/product_white_fabric.png",
    name_en:"Japanese Toyobo Cream", name_ar:"قماش تويوبو ياباني كريمي",
    desc_en:"Japanese Toyobo in cream shade, 3.5m. Warm elegant tone perfect for winter jubbas and thobes.",
    desc_ar:"قماش تويوبو ياباني بلون كريمي، ٣.٥ متر. لون دافئ أنيق مثالي لجُبب وثياب الشتاء.",
    price:225, old_price:280, badge:"", sizes:["3m","3.5m","4m","4.5m"] },
  { id:40, cat:"fabric", img:"images/product_white_fabric.png",
    name_en:"Chinese Polyester Blend", name_ar:"قماش بوليستر صيني",
    desc_en:"Chinese polyester-cotton blend, 3.5m. Wrinkle-free and easy maintenance. Affordable everyday option.",
    desc_ar:"قماش مزيج بوليستر وقطن صيني، ٣.٥ متر. خالي من التجعد وسهل العناية. خيار يومي بأسعار معقولة.",
    price:90, old_price:0, badge:"Budget", sizes:["3m","3.5m","4m","4.5m"] },
  { id:41, cat:"fabric", img:"images/product_white_fabric.png",
    name_en:"Korean Oxford White", name_ar:"قماش أكسفورد كوري أبيض",
    desc_en:"Korean Oxford weave white fabric, 3.5m. Textured finish with excellent body. Ideal for structured thobes.",
    desc_ar:"قماش أكسفورد كوري أبيض منسوج، ٣.٥ متر. لمسة محبّبة مع هيكل ممتاز. مثالي للثياب المهيكلة.",
    price:195, old_price:0, badge:"", sizes:["3m","3.5m","4m","4.5m"] },
  { id:42, cat:"fabric", img:"images/product_white_fabric.png",
    name_en:"Japanese Pure Silk", name_ar:"حرير ياباني خالص",
    desc_en:"Pure Japanese silk fabric, 3.5m. The ultimate luxury for special occasion thobes and bisht lining.",
    desc_ar:"قماش حرير ياباني خالص، ٣.٥ متر. الفخامة المطلقة لثياب المناسبات الخاصة وبطانة البشت.",
    price:450, old_price:0, badge:"Luxury", sizes:["3m","3.5m","4m","4.5m"] },
];

const defaultCategories = [
  { id:"thobe", img:"images/product_saudi_thobe.png", name_en:"Saudi Thobes", name_ar:"الثياب السعودية", count:3,
    desc_en:"Custom-tailored Saudi thobes crafted to your measurements", desc_ar:"ثياب سعودية مفصّلة حسب مقاساتك" },
  { id:"emirati", img:"images/product_emirati_thobe.png", name_en:"Emirati Kanduras", name_ar:"الكندورة الإماراتية", count:4,
    desc_en:"Bespoke Emirati kanduras with traditional tarboosh — custom-made", desc_ar:"كندورات إماراتية بالطربوش التقليدي — مصنوعة حسب الطلب" },
  { id:"qatari", img:"images/product_qatari_thobe.png", name_en:"Qatari Thobes", name_ar:"الثياب القطرية", count:4,
    desc_en:"Custom-tailored Qatari thobes with distinctive collar design", desc_ar:"ثياب قطرية مفصّلة بتصميم ياقة مميز" },
  { id:"kuwaiti", img:"images/product_kuwaiti_thobe.png", name_en:"Kuwaiti Dishdashas", name_ar:"الدشاديش الكويتية", count:4,
    desc_en:"Bespoke Kuwaiti dishdashas — expertly custom-tailored", desc_ar:"دشاديش كويتية — مفصّلة بخبرة حسب الطلب" },
  { id:"jubba", img:"images/product_jubba.png", name_en:"Jubbas", name_ar:"الجُبب", count:2,
    desc_en:"Elegant jubbas with embroidery for special occasions", desc_ar:"جُبب أنيقة بتطريز للمناسبات الخاصة" },
  { id:"saideria", img:"images/product_saideria.png", name_en:"Saiderias", name_ar:"الصداري", count:2,
    desc_en:"Premium cotton saiderias — essential undergarments", desc_ar:"صداري قطنية فاخرة — القطع الأساسية" },
  { id:"fabric", img:"images/product_white_fabric.png", name_en:"Fabrics", name_ar:"الأقمشة", count:22,
    desc_en:"Japanese, Chinese, Korean, Turkish, Egyptian & European fabrics", desc_ar:"أقمشة يابانية وصينية وكورية وتركية ومصرية وأوروبية" },
];

const defaultBranches = [
  { id:1, name_en: "Main Branch", name_ar: "الفرع الرئيسي", lat: 24.7136, lng: 46.6753, address: "Riyadh" }
];
